INSERT INTO specializations VALUES (DEFAULT, 'Cardiologist');
INSERT INTO specializations VALUES (DEFAULT, 'Dentist');
INSERT INTO specializations VALUES (DEFAULT, 'Dermatologist');
INSERT INTO specializations VALUES (DEFAULT, 'Endocrinologist');
INSERT INTO specializations VALUES (DEFAULT, 'Gastroenterologist');
INSERT INTO specializations VALUES (DEFAULT, 'Gynecologist');
INSERT INTO specializations VALUES (DEFAULT, 'Neurologist');
INSERT INTO specializations VALUES (DEFAULT, 'Ophthalmologist');
INSERT INTO specializations VALUES (DEFAULT, 'Orthopedist');
INSERT INTO specializations VALUES (DEFAULT, 'Pediatrician');

INSERT INTO doctors VALUES ('123456789', '123456789123', 
                            '2022-12-05'::date, 
                            'Azamat', 
                            'Yerzhanuly', 
                            'Yerzhanuly', 
                            'A', 
                            '87470842103', 
                            1, 
                            2, 
                            4, 
                            'image.png', 
                            'Bottom', 
                            5000, 
                            'Details', 
                            'Bachelor', 
                            2.5, 
                            'Kabanbay Batyr 54'),

                            ('123456788', 
                            '123456789122', 
                            '2022-12-05'::date, 
                            'Lenar', 
                            'Yerzhanuly', 
                            'Yerzhanuly', 
                            'A', 
                            '87470842102', 
                            2, 
                            1, 
                            5, 
                            'image.png', 
                            'Top', 
                            2500, 
                            'Details', 
                            'Master', 
                            2.5, 
                            'Kabanbay Batyr 53'),

                            ('123456787', 
                            '123456789121', 
                            '2022-12-05'::date, 
                            'Azamat', 
                            'Yerzhanuly', 
                            'Shakirov', 
                            'A', 
                            '87470842101', 
                            3, 
                            4, 
                            2, 
                            'image.png', 
                            'Switch', 
                            3000, 
                            'Details', 
                            'Master', 
                            2.5, 
                            'Kabanbay Batyr 52'),

                            ('123456786', 
                            '123456789120', 
                            '2022-12-05'::date, 
                            'Lenar', 
                            'Shakirov', 
                            'Shakirov', 
                            'A', 
                            '87470842100', 
                            4, 
                            3, 
                            6, 
                            'image.png', 
                            'Bottom', 
                            1000, 
                            'Details', 
                            'PhD', 
                            2.5, 
                            'Kabanbay Batyr 51');